version: "3"

services:
  app:
    image: x11-gui-app:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command:
      - xclock
    network_mode: host
